package X;

import android.util.SparseArray;
import com.AssemMods.translator.Language;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;

/* renamed from: X.28f  reason: invalid class name */
public abstract class AnonymousClass28f {
    public static final AnonymousClass00O A00;
    public static final AnonymousClass00O A01;
    public static final AnonymousClass00O A02;
    public static final C29201aD A03;
    public static final Set A04 = new LinkedHashSet(Arrays.asList(new String[]{"af", "sq", "am", Language.ARABIC, "az", Language.BENGALI, "bg", "ca", "zh-CN", "zh-HK", "zh-TW", "hr", "cs", "da", "nl", Language.ENGLISH, "et", "fil", "fi", Language.FRENCH, Language.GERMAN, "el", Language.GUJARATI, "ha", "he", Language.HINDI, "hu", "id", "ga", Language.ITALIAN, Language.JAPANESE, Language.KANNADA, "kk", "ko", "lo", "lv", "lt", "mk", "ms", Language.MALAYALAM, Language.MARATHI, "nb", "om", "fa", "pl", "pt-BR", "pt-PT", Language.PUNJABI, "ro", Language.RUSSIAN, "sr", "sk", "sl", Language.SPANISH, "sw", "sv", "tl", Language.TAMIL, Language.TELUGU, "th", Language.TURKISH, "uk", Language.URDU, "uz", Language.VIETNAMESE}));

    static {
        AnonymousClass00O r1 = new AnonymousClass00O(24);
        A02 = r1;
        r1.put("am", 4768);
        r1.put(Language.ARABIC, 1593);
        r1.put("az", 399);
        r1.put(Language.BENGALI, 2437);
        r1.put("zh-Hans", 35831);
        r1.put("zh-Hant", 35531);
        r1.put("hr", 273);
        r1.put(Language.GUJARATI, 2693);
        r1.put(Language.HINDI, 2308);
        r1.put(Language.KANNADA, 3205);
        r1.put("kk", 1201);
        r1.put("lo", 3713);
        r1.put("mk", 1107);
        r1.put(Language.MALAYALAM, 3333);
        r1.put(Language.MARATHI, 2418);
        r1.put("fa", 1740);
        r1.put(Language.PUNJABI, 2576);
        r1.put("ro", 539);
        r1.put("sr", 1115);
        r1.put(Language.TAMIL, 2949);
        r1.put(Language.TELUGU, 3077);
        r1.put("th", 3585);
        r1.put("uk", 1111);
        r1.put(Language.URDU, 1746);
        AnonymousClass00O r12 = new AnonymousClass00O(14);
        A01 = r12;
        r12.put(Language.ARABIC, AnonymousClass1WH.A0D(1632));
        r12.put(Language.BENGALI, AnonymousClass1WH.A0D(2534));
        r12.put("fa", AnonymousClass1WH.A0D(1776));
        r12.put(Language.GUJARATI, AnonymousClass1WH.A0D(2790));
        r12.put(Language.HINDI, AnonymousClass1WH.A0D(2406));
        r12.put(Language.KANNADA, AnonymousClass1WH.A0D(3302));
        r12.put("lo", AnonymousClass1WH.A0D(3792));
        r12.put(Language.MALAYALAM, AnonymousClass1WH.A0D(3430));
        r12.put(Language.MARATHI, AnonymousClass1WH.A0D(2406));
        r12.put(Language.PUNJABI, AnonymousClass1WH.A0D(2662));
        r12.put(Language.TAMIL, AnonymousClass1WH.A0D(3046));
        r12.put(Language.TELUGU, AnonymousClass1WH.A0D(3174));
        r12.put("th", AnonymousClass1WH.A0D(3664));
        r12.put(Language.URDU, AnonymousClass1WH.A0D(1776));
        C29201aD r14 = new C29201aD(47);
        A03 = r14;
        r14.A03("AF", new String[]{"fa-AF", "en-GB"});
        r14.A03("AL", new String[]{"sq-AL", "en-GB"});
        r14.A03("DZ", new String[]{"ar-DZ", "fr-DZ"});
        r14.A03("AD", new String[]{"ca-AD", "es-ES", "pt-PT", "fr-FR"});
        r14.A03("AR", new String[]{"es-AR"});
        r14.A03("AU", new String[]{"en-AU"});
        r14.A03("AT", new String[]{"de-AT"});
        r14.A03("AZ", new String[]{"az-AZ", "ru-RU", "tr-TR"});
        r14.A03("BH", new String[]{"ar-BH", "en-GB"});
        r14.A03("BD", new String[]{"bn-BD", "en-GB"});
        r14.A03("BE", new String[]{"nl-BE", "fr-BE"});
        r14.A03("BO", new String[]{"es-BO"});
        r14.A03("BA", new String[]{"hr-BA", "sr-BA"});
        r14.A03("BR", new String[]{"pt-BR"});
        r14.A03("BN", new String[]{"ms-BN", "en-GB", "zh-CN", "zh-TW"});
        r14.A03("BF", new String[]{"fr-BF"});
        r14.A03("BI", new String[]{"en-BI", "fr-BI", "sw-TZ"});
        r14.A03("CM", new String[]{"fr-CM", "en-CM"});
        r14.A03("CA", new String[]{"en-CA", "fr-CA"});
        r14.A03("TD", new String[]{"fr-TD", "ar-TD"});
        r14.A03("CL", new String[]{"es-CL"});
        r14.A03("CO", new String[]{"es-CO"});
        r14.A03("KM", new String[]{"fr-KM", "en-GB", "ar-KM"});
        r14.A03("CD", new String[]{"fr-CD", "sw-CD"});
        r14.A03("CR", new String[]{"es-CR"});
        r14.A03("CU", new String[]{"es-CU"});
        r14.A03("CZ", new String[]{"cs-CZ"});
        r14.A03("DJ", new String[]{"fr-DJ", "en-GB", "ar-DJ"});
        r14.A03("DO", new String[]{"es-DO"});
        r14.A03("EC", new String[]{"es-EC"});
        r14.A03("EG", new String[]{"ar-EG"});
        r14.A03("SV", new String[]{"es-SV"});
        r14.A03("ER", new String[]{"en-ER", "ar-ER"});
        r14.A03("FI", new String[]{"fi-FI"});
        r14.A03("FR", new String[]{"fr-FR"});
        r14.A03("DE", new String[]{"de-DE"});
        r14.A03("GH", new String[]{"en-GH"});
        r14.A03("GT", new String[]{"es-GT"});
        r14.A03("HT", new String[]{"fr-HT"});
        r14.A03("HN", new String[]{"es-HN"});
        r14.A03("IN", new String[]{"en-IN", "hi-IN", "mr-IN", "gu-IN", "ta-IN", "bn-IN", "te-IN", "kn-IN", "ml-IN", "pa-IN", "ur-IN"});
        r14.A03("IR", new String[]{"fa-IR", "en-GB"});
        r14.A03("IQ", new String[]{"ar-iq"});
        r14.A03("IE", new String[]{"en-IE", "ga-IE"});
        r14.A03("IL", new String[]{"iw-IL", "ar-IL", "en-IL", "ru-RU"});
        r14.A03("IT", new String[]{"it-IT"});
        r14.A03("CI", new String[]{"fr-CI"});
        r14.A03("JO", new String[]{"ar-JO", "en-GB"});
        r14.A03("KZ", new String[]{"kk-KZ", "ru-KZ"});
        r14.A03("KE", new String[]{"en-KE", "sw-KE"});
        r14.A03("XK", new String[]{"sq-XK", "sr-XK", "hr-HR"});
        r14.A03("KW", new String[]{"ar-KW", "en-GB"});
        r14.A03("KG", new String[]{"ru-KG"});
        r14.A03("LA", new String[]{"lo-LA", "th-TH", "en-GB"});
        r14.A03("LB", new String[]{"ar-LB", "en-GB", "fr-FR"});
        r14.A03("LY", new String[]{"ar-LY"});
        r14.A03("MK", new String[]{"mk-MK", "sq-MK", "tr-TR", "hr-HR", "sr-RS"});
        r14.A03("MW", new String[]{"en-MW", "sw-TZ"});
        r14.A03("MY", new String[]{"ms-MY", "en-MY", "zh-CN", "zh-TW", "ta-MY"});
        r14.A03("ML", new String[]{"fr-ML"});
        r14.A03("MR", new String[]{"ar-MR", "fr-MR"});
        r14.A03("MX", new String[]{Language.SPANISH});
        r14.A03("MD", new String[]{"ro-MD", "ru-MD"});
        r14.A03("MA", new String[]{"ar-MA", "fr-MA"});
        r14.A03("MZ", new String[]{"pt-MZ"});
        r14.A03("NL", new String[]{"nl-NL"});
        r14.A03("NI", new String[]{"es-NI"});
        r14.A03("NE", new String[]{"ar-TD", "fr-NE"});
        r14.A03("OM", new String[]{"ar-OM", "en-GB"});
        r14.A03("PK", new String[]{"en-PK", "ur-PK"});
        r14.A03("PA", new String[]{"es-PA"});
        r14.A03("PY", new String[]{"es-PY"});
        r14.A03("PE", new String[]{"es-PE"});
        r14.A03("PH", new String[]{"en-PH", "fil-PH", "es-PH", "ar-EG"});
        r14.A03("PL", new String[]{"pl-PL"});
        r14.A03("PT", new String[]{"pt-PT"});
        r14.A03("QA", new String[]{"ar-QA", "en-GB"});
        r14.A03("RO", new String[]{"ro-RO"});
        r14.A03("RU", new String[]{"ru-RU"});
        r14.A03("RW", new String[]{"en-RW", "fr-RW", "sw-TZ"});
        r14.A03("SA", new String[]{"ar-SA", "en-GB"});
        r14.A03("SN", new String[]{"fr-SN"});
        r14.A03("SG", new String[]{"en-SG"});
        r14.A03("SI", new String[]{"sl-SI", "en-SI", "hr-HR", "it-IT", "hu-HU", "sr-RS"});
        r14.A03("SO", new String[]{"en-GB", "ar-SO"});
        r14.A03("ZA", new String[]{"en-ZA"});
        r14.A03("SS", new String[]{"en-SS", "ar-SS"});
        r14.A03("ES", new String[]{"es-ES"});
        r14.A03("LK", new String[]{"en-GB"});
        r14.A03("SD", new String[]{"ar-SD", "en-SD"});
        r14.A03("CH", new String[]{"de-CH", "fr-CH"});
        r14.A03("SY", new String[]{"ar-SY"});
        r14.A03("TZ", new String[]{"en-TZ", "sw-TZ"});
        r14.A03("TN", new String[]{"ar-TN", "fr-TN"});
        r14.A03("TR", new String[]{"tr-TR", Language.ARABIC});
        r14.A03("UG", new String[]{"en-UG", "sw-UG"});
        r14.A03("UA", new String[]{"uk-UA", "ru-UA"});
        r14.A03("AE", new String[]{"ar-AE", "en-GB"});
        r14.A03("GB", new String[]{"en-GB", "ga-IE"});
        r14.A03("US", new String[]{"en-US", "es-LA", "pt-BR", "ar-AE", "zh-CN", "fr-FR", "ru-RU", "vi-VN", "ko-KR"});
        r14.A03("UZ", new String[]{"uz-UZ", "ru-RU"});
        r14.A03("VE", new String[]{"es-VE"});
        r14.A03("ZM", new String[]{"en-ZM"});
        r14.A03("ZW", new String[]{"en-ZW"});
        r14.A03("QQ", new String[]{"az-AZ", "ca-ES", "en-US", "es-ES", "fil-PH", "fr-FR", "ga-IE", "hr-HR", "it-IT", "sw-TZ", "uz-UZ", "hu-HU", "ms-MY", "sq-AL", "sl-SI", "tr-TR", "kk-KZ", "ru-RU", "sr-RS", "uk-UA", "iw-IL", "ur-PK", "fa-IR", "ar-EG", "hi-IN", "bn-BD", "pa-IN", "te-IN", "mr-IN", "ta-IN", "gu-IN", "kn-IN", "ml-IN", "th-TH", "lo-LA", "zh-CN", "zh-TW", "ha-NG", "am-ET", "om-ET"});
        C29201aD r30 = AnonymousClass49S.A00;
        SparseArray sparseArray = r30.A00;
        int size = sparseArray.size();
        for (int i2 = 0; i2 < size; i2++) {
            if (i2 < 0 || i2 >= sparseArray.size()) {
                StringBuilder sb = new StringBuilder("Invalid index ");
                sb.append(i2);
                sb.append(" when fetching flavor specific country language data");
                throw new ArrayIndexOutOfBoundsException(sb.toString());
            }
            int keyAt = sparseArray.keyAt(i2);
            StringBuilder sb2 = new StringBuilder("");
            sb2.append((char) ((keyAt / 26) + 65));
            sb2.append((char) ((keyAt % 26) + 65));
            String obj = sb2.toString();
            A03.A03(obj, r30.A01(obj));
        }
        AnonymousClass00O r13 = new AnonymousClass00O(62);
        A00 = r13;
        r13.put("af", "Afrikaans");
        r13.put("sq", "Shqip");
        r13.put("am", "አማርኛ");
        r13.put(Language.ARABIC, "العربية");
        r13.put("az", "Azərbaycan dili");
        r13.put(Language.BENGALI, "বাংলা");
        r13.put("bg", "Български");
        r13.put("ca", "Català");
        r13.put("zh-Hans", "简体中文");
        r13.put("zh-Hant", "繁體中文");
        r13.put("zh-HK", "繁體中文（香港）");
        r13.put("zh-TW", "繁體中文（台灣)");
        r13.put("hr", "Hrvatski");
        r13.put("cs", "Čeština");
        r13.put("nl", "Nederlands");
        r13.put(Language.ENGLISH, "English");
        r13.put(Language.GERMAN, "Deutsch");
        r13.put("el", "Ελληνικά");
        r13.put("et", "Eesti");
        r13.put("fil", "Filipino");
        r13.put("fi", "Suomi");
        r13.put(Language.FRENCH, "Français");
        r13.put(Language.GUJARATI, "ગુજરાતી");
        r13.put("ha", "Hausa");
        r13.put("iw", "עברית");
        r13.put(Language.HINDI, "हिन्दी");
        r13.put("hu", "Magyar");
        r13.put("in", "Bahasa Indonesia");
        r13.put("ga", "Gaeilge");
        r13.put(Language.ITALIAN, "Italiano");
        r13.put(Language.JAPANESE, "日本語");
        r13.put(Language.KANNADA, "ಕನ್ನಡ");
        r13.put("kk", "Қазақ тілі");
        r13.put("ko", "한국어");
        r13.put("lo", "ລາວ");
        r13.put("lv", "Latviešu");
        r13.put("lt", "Lietuvių");
        r13.put("mk", "Македонски");
        r13.put("ms", "Melayu");
        r13.put(Language.MALAYALAM, "മലയാളം");
        r13.put(Language.MARATHI, "मराठी");
        r13.put("nb", "Norsk bokmål");
        r13.put("om", "Oromoo");
        r13.put("fa", "فارسی");
        r13.put("pl", "Polski");
        r13.put(Language.PORTUGUESE, "Português");
        r13.put("pt-BR", "Português (Brasil)");
        r13.put("pt-PT", "Português (Portugal)");
        r13.put(Language.PUNJABI, "ਪੰਜਾਬੀ");
        r13.put("ro", "Română");
        r13.put(Language.RUSSIAN, "Русский");
        r13.put("sr", "Српски");
        r13.put("sk", "Slovenčina");
        r13.put("sl", "Slovenščina");
        r13.put(Language.SPANISH, "Español");
        r13.put("sw", "Kiswahili");
        r13.put("sv", "Svenska");
        r13.put("tl", "Filipino");
        r13.put(Language.TAMIL, "தமிழ்");
        r13.put(Language.TELUGU, "తెలుగు");
        r13.put("th", "ไทย");
        r13.put(Language.TURKISH, "Türkçe");
        r13.put("uk", "Українська");
        r13.put(Language.URDU, "اردو");
        r13.put("uz", "O‘zbek");
        r13.put(Language.VIETNAMESE, "Tiếng Việt");
    }
}
