package X;

/* renamed from: X.21I  reason: invalid class name */
public final class AnonymousClass21I extends C16470t7 {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Double A08;
    public Double A09;
    public Double A0A;
    public Integer A0B;
    public Integer A0C;
    public Integer A0D;
    public Integer A0E;
    public Integer A0F;
    public Integer A0G;
    public Integer A0H;
    public Integer A0I;
    public Integer A0J;
    public Long A0K;
    public Long A0L;
    public Long A0M;
    public Long A0N;
    public Long A0O;
    public Long A0P;
    public Long A0Q;
    public Long A0R;
    public Long A0S;
    public Long A0T;
    public Long A0U;
    public Long A0V;
    public Long A0W;
    public Long A0X;
    public Long A0Y;
    public Long A0Z;
    public Long A0a;
    public Long A0b;
    public Long A0c;
    public Long A0d;
    public Long A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;

    public AnonymousClass21I() {
        super(1588, new AnonymousClass00F(1, 10, 10), 0, -1);
    }

    public void serialize(C29081Zz r3) {
        r3.AdT(43, this.A0B);
        r3.AdT(34, this.A0f);
        r3.AdT(32, this.A0g);
        r3.AdT(33, this.A0h);
        r3.AdT(45, this.A08);
        r3.AdT(28, this.A0K);
        r3.AdT(31, this.A0L);
        r3.AdT(30, this.A00);
        r3.AdT(29, this.A0M);
        r3.AdT(49, this.A01);
        r3.AdT(46, this.A0N);
        r3.AdT(42, this.A0C);
        r3.AdT(4, this.A0O);
        r3.AdT(10, this.A0P);
        r3.AdT(41, this.A0i);
        r3.AdT(37, this.A0Q);
        r3.AdT(38, this.A0R);
        r3.AdT(5, this.A0j);
        r3.AdT(36, this.A02);
        r3.AdT(16, this.A03);
        r3.AdT(13, this.A04);
        r3.AdT(40, this.A0D);
        r3.AdT(7, this.A09);
        r3.AdT(1, this.A0E);
        r3.AdT(6, this.A0S);
        r3.AdT(12, this.A0F);
        r3.AdT(9, this.A0T);
        r3.AdT(3, this.A0U);
        r3.AdT(8, this.A0V);
        r3.AdT(15, this.A0W);
        r3.AdT(39, this.A0G);
        r3.AdT(44, this.A0H);
        r3.AdT(35, this.A0I);
        r3.AdT(14, this.A0X);
        r3.AdT(17, this.A0Y);
        r3.AdT(20, this.A0Z);
        r3.AdT(19, this.A05);
        r3.AdT(18, this.A0a);
        r3.AdT(27, this.A0A);
        r3.AdT(22, this.A0b);
        r3.AdT(25, this.A0c);
        r3.AdT(24, this.A06);
        r3.AdT(26, this.A07);
        r3.AdT(23, this.A0d);
        r3.AdT(21, this.A0e);
        r3.AdT(48, this.A0J);
    }

    public String toString() {
        StringBuilder sb = new StringBuilder("WamMediaUpload2 {");
        Integer num = this.A0B;
        C16470t7.appendFieldToStringBuilder(sb, "connectionType", num == null ? null : num.toString());
        C16470t7.appendFieldToStringBuilder(sb, "debugMediaException", this.A0f);
        C16470t7.appendFieldToStringBuilder(sb, "debugMediaIp", this.A0g);
        C16470t7.appendFieldToStringBuilder(sb, "debugUrl", this.A0h);
        C16470t7.appendFieldToStringBuilder(sb, "estimatedBandwidth", this.A08);
        C16470t7.appendFieldToStringBuilder(sb, "finalizeConnectT", this.A0K);
        C16470t7.appendFieldToStringBuilder(sb, "finalizeHttpCode", this.A0L);
        C16470t7.appendFieldToStringBuilder(sb, "finalizeIsReuse", this.A00);
        C16470t7.appendFieldToStringBuilder(sb, "finalizeNetworkT", this.A0M);
        C16470t7.appendFieldToStringBuilder(sb, "isViewOnce", this.A01);
        C16470t7.appendFieldToStringBuilder(sb, "mediaId", this.A0N);
        Integer num2 = this.A0C;
        C16470t7.appendFieldToStringBuilder(sb, "networkStack", num2 == null ? null : num2.toString());
        C16470t7.appendFieldToStringBuilder(sb, "overallAttemptCount", this.A0O);
        C16470t7.appendFieldToStringBuilder(sb, "overallConnBlockFetchT", this.A0P);
        C16470t7.appendFieldToStringBuilder(sb, "overallConnectionClass", this.A0i);
        C16470t7.appendFieldToStringBuilder(sb, "overallCumT", this.A0Q);
        C16470t7.appendFieldToStringBuilder(sb, "overallCumUserVisibleT", this.A0R);
        C16470t7.appendFieldToStringBuilder(sb, "overallDomain", this.A0j);
        C16470t7.appendFieldToStringBuilder(sb, "overallIsFinal", this.A02);
        C16470t7.appendFieldToStringBuilder(sb, "overallIsForward", this.A03);
        C16470t7.appendFieldToStringBuilder(sb, "overallIsManual", this.A04);
        Integer num3 = this.A0D;
        C16470t7.appendFieldToStringBuilder(sb, "overallMediaKeyReuse", num3 == null ? null : num3.toString());
        C16470t7.appendFieldToStringBuilder(sb, "overallMediaSize", this.A09);
        Integer num4 = this.A0E;
        C16470t7.appendFieldToStringBuilder(sb, "overallMediaType", num4 == null ? null : num4.toString());
        C16470t7.appendFieldToStringBuilder(sb, "overallMmsVersion", this.A0S);
        Integer num5 = this.A0F;
        C16470t7.appendFieldToStringBuilder(sb, "overallOptimisticFlag", num5 == null ? null : num5.toString());
        C16470t7.appendFieldToStringBuilder(sb, "overallQueueT", this.A0T);
        C16470t7.appendFieldToStringBuilder(sb, "overallRetryCount", this.A0U);
        C16470t7.appendFieldToStringBuilder(sb, "overallT", this.A0V);
        C16470t7.appendFieldToStringBuilder(sb, "overallTranscodeT", this.A0W);
        Integer num6 = this.A0G;
        C16470t7.appendFieldToStringBuilder(sb, "overallUploadMode", num6 == null ? null : num6.toString());
        Integer num7 = this.A0H;
        C16470t7.appendFieldToStringBuilder(sb, "overallUploadOrigin", num7 == null ? null : num7.toString());
        Integer num8 = this.A0I;
        C16470t7.appendFieldToStringBuilder(sb, "overallUploadResult", num8 == null ? null : num8.toString());
        C16470t7.appendFieldToStringBuilder(sb, "overallUserVisibleT", this.A0X);
        C16470t7.appendFieldToStringBuilder(sb, "resumeConnectT", this.A0Y);
        C16470t7.appendFieldToStringBuilder(sb, "resumeHttpCode", this.A0Z);
        C16470t7.appendFieldToStringBuilder(sb, "resumeIsReuse", this.A05);
        C16470t7.appendFieldToStringBuilder(sb, "resumeNetworkT", this.A0a);
        C16470t7.appendFieldToStringBuilder(sb, "uploadBytesTransferred", this.A0A);
        C16470t7.appendFieldToStringBuilder(sb, "uploadConnectT", this.A0b);
        C16470t7.appendFieldToStringBuilder(sb, "uploadHttpCode", this.A0c);
        C16470t7.appendFieldToStringBuilder(sb, "uploadIsReuse", this.A06);
        C16470t7.appendFieldToStringBuilder(sb, "uploadIsStreaming", this.A07);
        C16470t7.appendFieldToStringBuilder(sb, "uploadNetworkT", this.A0d);
        C16470t7.appendFieldToStringBuilder(sb, "uploadResumePoint", this.A0e);
        Integer num9 = this.A0J;
        C16470t7.appendFieldToStringBuilder(sb, "uploadSource", num9 == null ? null : num9.toString());
        sb.append("}");
        return sb.toString();
    }
}
