package X;

/* renamed from: X.2D8  reason: invalid class name */
public final class AnonymousClass2D8 extends C16470t7 {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Integer A0G;
    public Integer A0H;
    public Integer A0I;
    public Integer A0J;
    public Integer A0K;
    public Integer A0L;
    public Integer A0M;
    public Integer A0N;
    public Long A0O;
    public Long A0P;
    public Long A0Q;
    public Long A0R;
    public Long A0S;
    public Long A0T;
    public Long A0U;
    public Long A0V;
    public Long A0W;
    public Long A0X;
    public Long A0Y;
    public Long A0Z;
    public Long A0a;
    public Long A0b;
    public Long A0c;
    public Long A0d;
    public Long A0e;
    public Long A0f;
    public Long A0g;
    public Long A0h;
    public Long A0i;
    public Long A0j;
    public Long A0k;
    public Long A0l;
    public Long A0m;
    public Long A0n;
    public Long A0o;
    public Long A0p;
    public Long A0q;
    public Long A0r;
    public Long A0s;
    public Long A0t;
    public Long A0u;
    public Long A0v;
    public Long A0w;
    public Long A0x;
    public Long A0y;
    public Long A0z;
    public Long A10;
    public Long A11;
    public Long A12;
    public Long A13;
    public Long A14;
    public Long A15;
    public Long A16;
    public Long A17;
    public Long A18;
    public Long A19;
    public Long A1A;
    public Long A1B;
    public Long A1C;
    public Long A1D;
    public Long A1E;
    public Long A1F;
    public String A1G;
    public String A1H;
    public String A1I;
    public String A1J;

    public AnonymousClass2D8() {
        super(1644, new AnonymousClass00F(1, 1, 1), 0, -1);
    }

    public void serialize(C29081Zz r3) {
        r3.AdT(56, this.A0O);
        r3.AdT(60, this.A0G);
        r3.AdT(65, this.A0P);
        r3.AdT(33, this.A0H);
        r3.AdT(30, this.A0Q);
        r3.AdT(29, this.A0R);
        r3.AdT(27, this.A0S);
        r3.AdT(26, this.A0T);
        r3.AdT(70, this.A0U);
        r3.AdT(71, this.A0V);
        r3.AdT(72, this.A0W);
        r3.AdT(78, this.A0X);
        r3.AdT(73, this.A0Y);
        r3.AdT(74, this.A0Z);
        r3.AdT(88, this.A00);
        r3.AdT(86, this.A0a);
        r3.AdT(15, this.A0b);
        r3.AdT(8, this.A0I);
        r3.AdT(79, this.A0c);
        r3.AdT(2, this.A0J);
        r3.AdT(44, this.A0d);
        r3.AdT(41, this.A0e);
        r3.AdT(40, this.A0f);
        r3.AdT(59, this.A0K);
        r3.AdT(47, this.A1G);
        r3.AdT(46, this.A1H);
        r3.AdT(14, this.A0g);
        r3.AdT(13, this.A0h);
        r3.AdT(69, this.A0i);
        r3.AdT(25, this.A0j);
        r3.AdT(22, this.A0L);
        r3.AdT(57, this.A0k);
        r3.AdT(75, this.A01);
        r3.AdT(87, this.A0M);
        r3.AdT(51, this.A0l);
        r3.AdT(52, this.A0m);
        r3.AdT(19, this.A0n);
        r3.AdT(6, this.A02);
        r3.AdT(5, this.A03);
        r3.AdT(10, this.A04);
        r3.AdT(32, this.A05);
        r3.AdT(36, this.A06);
        r3.AdT(35, this.A07);
        r3.AdT(37, this.A08);
        r3.AdT(62, this.A09);
        r3.AdT(9, this.A0A);
        r3.AdT(92, this.A0B);
        r3.AdT(55, this.A0o);
        r3.AdT(96, this.A0p);
        r3.AdT(4, this.A0q);
        r3.AdT(3, this.A0r);
        r3.AdT(12, this.A0s);
        r3.AdT(11, this.A0t);
        r3.AdT(68, this.A0C);
        r3.AdT(38, this.A0u);
        r3.AdT(39, this.A0v);
        r3.AdT(42, this.A0w);
        r3.AdT(61, this.A0x);
        r3.AdT(64, this.A0y);
        r3.AdT(63, this.A0z);
        r3.AdT(58, this.A10);
        r3.AdT(97, this.A11);
        r3.AdT(98, this.A12);
        r3.AdT(21, this.A13);
        r3.AdT(80, this.A14);
        r3.AdT(93, this.A0D);
        r3.AdT(94, this.A0E);
        r3.AdT(20, this.A15);
        r3.AdT(99, this.A0F);
        r3.AdT(31, this.A16);
        r3.AdT(7, this.A17);
        r3.AdT(50, this.A18);
        r3.AdT(49, this.A19);
        r3.AdT(66, this.A1I);
        r3.AdT(67, this.A1J);
        r3.AdT(28, this.A1A);
        r3.AdT(85, this.A0N);
        r3.AdT(76, this.A1B);
        r3.AdT(18, this.A1C);
        r3.AdT(17, this.A1D);
        r3.AdT(16, this.A1E);
        r3.AdT(77, this.A1F);
    }

    public String toString() {
        StringBuilder sb = new StringBuilder("WamChatMessageCounts {");
        C16470t7.appendFieldToStringBuilder(sb, "awayMsgsSent", this.A0O);
        Integer num = this.A0G;
        C16470t7.appendFieldToStringBuilder(sb, "bizCatalogType", num == null ? null : num.toString());
        C16470t7.appendFieldToStringBuilder(sb, "bizConversationDepth", this.A0P);
        Integer num2 = this.A0H;
        C16470t7.appendFieldToStringBuilder(sb, "blockReason", num2 == null ? null : num2.toString());
        C16470t7.appendFieldToStringBuilder(sb, "broadcastMsgsReceived", this.A0Q);
        C16470t7.appendFieldToStringBuilder(sb, "broadcastMsgsSent", this.A0R);
        C16470t7.appendFieldToStringBuilder(sb, "callOffersReceived", this.A0S);
        C16470t7.appendFieldToStringBuilder(sb, "callOffersSent", this.A0T);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultBusy", this.A0U);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultCancelled", this.A0V);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultConnected", this.A0W);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultError", this.A0X);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultMissed", this.A0Y);
        C16470t7.appendFieldToStringBuilder(sb, "callsResultRejected", this.A0Z);
        C16470t7.appendFieldToStringBuilder(sb, "canEditDmSettings", this.A00);
        C16470t7.appendFieldToStringBuilder(sb, "cartViews", this.A0a);
        C16470t7.appendFieldToStringBuilder(sb, "chatEphemeralityDuration", this.A0b);
        Integer num3 = this.A0I;
        C16470t7.appendFieldToStringBuilder(sb, "chatMuted", num3 == null ? null : num3.toString());
        C16470t7.appendFieldToStringBuilder(sb, "chatOverflowClicks", this.A0c);
        Integer num4 = this.A0J;
        C16470t7.appendFieldToStringBuilder(sb, "chatTypeInd", num4 == null ? null : num4.toString());
        C16470t7.appendFieldToStringBuilder(sb, "collectionInquiriesSent", this.A0d);
        C16470t7.appendFieldToStringBuilder(sb, "commerceMsgsReceived", this.A0e);
        C16470t7.appendFieldToStringBuilder(sb, "commerceMsgsSent", this.A0f);
        Integer num5 = this.A0K;
        C16470t7.appendFieldToStringBuilder(sb, "disappearingChatInitiator", num5 == null ? null : num5.toString());
        C16470t7.appendFieldToStringBuilder(sb, "entryPointConversionApp", this.A1G);
        C16470t7.appendFieldToStringBuilder(sb, "entryPointConversionSource", this.A1H);
        C16470t7.appendFieldToStringBuilder(sb, "ephemeralMessagesReceived", this.A0g);
        C16470t7.appendFieldToStringBuilder(sb, "ephemeralMessagesSent", this.A0h);
        C16470t7.appendFieldToStringBuilder(sb, "ephemeralMessagesUnreadExpired", this.A0i);
        C16470t7.appendFieldToStringBuilder(sb, "firstResponseTime", this.A0j);
        Integer num6 = this.A0L;
        C16470t7.appendFieldToStringBuilder(sb, "gaStatus", num6 == null ? null : num6.toString());
        C16470t7.appendFieldToStringBuilder(sb, "greetingMsgsSent", this.A0k);
        C16470t7.appendFieldToStringBuilder(sb, "groupContainsBiz", this.A01);
        Integer num7 = this.A0M;
        C16470t7.appendFieldToStringBuilder(sb, "groupInfoSetting", num7 == null ? null : num7.toString());
        C16470t7.appendFieldToStringBuilder(sb, "groupMembershipReplies", this.A0l);
        C16470t7.appendFieldToStringBuilder(sb, "groupPrivateReplies", this.A0m);
        C16470t7.appendFieldToStringBuilder(sb, "groupSize", this.A0n);
        C16470t7.appendFieldToStringBuilder(sb, "isAContact", this.A02);
        C16470t7.appendFieldToStringBuilder(sb, "isAGroup", this.A03);
        C16470t7.appendFieldToStringBuilder(sb, "isArchived", this.A04);
        C16470t7.appendFieldToStringBuilder(sb, "isBlocked", this.A05);
        C16470t7.appendFieldToStringBuilder(sb, "isCartAddClicked", this.A06);
        C16470t7.appendFieldToStringBuilder(sb, "isCommerceViewed", this.A07);
        C16470t7.appendFieldToStringBuilder(sb, "isCtaOnPdpClicked", this.A08);
        C16470t7.appendFieldToStringBuilder(sb, "isOppositePartyInitiated", this.A09);
        C16470t7.appendFieldToStringBuilder(sb, "isPinned", this.A0A);
        C16470t7.appendFieldToStringBuilder(sb, "isPnhEnabledChat", this.A0B);
        C16470t7.appendFieldToStringBuilder(sb, "labelledMsgs", this.A0o);
        C16470t7.appendFieldToStringBuilder(sb, "locationsSent", this.A0p);
        C16470t7.appendFieldToStringBuilder(sb, "messagesReceived", this.A0q);
        C16470t7.appendFieldToStringBuilder(sb, "messagesSent", this.A0r);
        C16470t7.appendFieldToStringBuilder(sb, "messagesStarred", this.A0s);
        C16470t7.appendFieldToStringBuilder(sb, "messagesUnread", this.A0t);
        C16470t7.appendFieldToStringBuilder(sb, "newThread", this.A0C);
        C16470t7.appendFieldToStringBuilder(sb, "ordersSent", this.A0u);
        C16470t7.appendFieldToStringBuilder(sb, "paymentsSent", this.A0v);
        C16470t7.appendFieldToStringBuilder(sb, "pdpInquiriesSent", this.A0w);
        C16470t7.appendFieldToStringBuilder(sb, "pdpViews", this.A0x);
        C16470t7.appendFieldToStringBuilder(sb, "profileReplies", this.A0y);
        C16470t7.appendFieldToStringBuilder(sb, "profileViews", this.A0z);
        C16470t7.appendFieldToStringBuilder(sb, "quickRepliesSent", this.A10);
        C16470t7.appendFieldToStringBuilder(sb, "reactionsReceived", this.A11);
        C16470t7.appendFieldToStringBuilder(sb, "reactionsSent", this.A12);
        C16470t7.appendFieldToStringBuilder(sb, "receiverDefaultDisappearingDuration", this.A13);
        C16470t7.appendFieldToStringBuilder(sb, "repliesSent", this.A14);
        C16470t7.appendFieldToStringBuilder(sb, "requestedPhoneNumber", this.A0D);
        C16470t7.appendFieldToStringBuilder(sb, "seenMaskedPhoneNumber", this.A0E);
        C16470t7.appendFieldToStringBuilder(sb, "senderDefaultDisappearingDuration", this.A15);
        C16470t7.appendFieldToStringBuilder(sb, "sharedPhoneNumber", this.A0F);
        C16470t7.appendFieldToStringBuilder(sb, "spamReports", this.A16);
        C16470t7.appendFieldToStringBuilder(sb, "startTime", this.A17);
        C16470t7.appendFieldToStringBuilder(sb, "statusReplies", this.A18);
        C16470t7.appendFieldToStringBuilder(sb, "statusViews", this.A19);
        C16470t7.appendFieldToStringBuilder(sb, "threadDs", this.A1I);
        C16470t7.appendFieldToStringBuilder(sb, "threadId", this.A1J);
        C16470t7.appendFieldToStringBuilder(sb, "totalCallDuration", this.A1A);
        Integer num8 = this.A0N;
        C16470t7.appendFieldToStringBuilder(sb, "typeOfGroup", num8 == null ? null : num8.toString());
        C16470t7.appendFieldToStringBuilder(sb, "videoCallsOffered", this.A1B);
        C16470t7.appendFieldToStringBuilder(sb, "viewOnceMessagesOpened", this.A1C);
        C16470t7.appendFieldToStringBuilder(sb, "viewOnceMessagesReceived", this.A1D);
        C16470t7.appendFieldToStringBuilder(sb, "viewOnceMessagesSent", this.A1E);
        C16470t7.appendFieldToStringBuilder(sb, "voiceCallsOffered", this.A1F);
        sb.append("}");
        return sb.toString();
    }
}
