package X;

import java.util.Set;

/* renamed from: X.1sb  reason: invalid class name and case insensitive filesystem */
public abstract class C39511sb {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;

    static {
        StringBuilder sb = new StringBuilder("SELECT ");
        String str = C16910tr.A00;
        sb.append(str);
        sb.append(" FROM ");
        sb.append("message_view");
        sb.append(" WHERE chat_row_id=? AND from_me=? AND key_id=?");
        A03 = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append("SELECT ");
        sb2.append(str);
        sb2.append(" FROM ");
        sb2.append("message_view");
        sb2.append(" WHERE ");
        sb2.append("chat_row_id = ?");
        sb2.append(" AND ");
        sb2.append("from_me = ?");
        sb2.append(" AND ");
        sb2.append("key_id = ?");
        A04 = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append("SELECT ");
        sb3.append(str);
        sb3.append(" FROM ");
        sb3.append("available_message_view");
        sb3.append(" WHERE ");
        sb3.append("chat_row_id");
        sb3.append(" = ? AND ");
        sb3.append("from_me");
        sb3.append(" = 1 AND ");
        sb3.append("message_type");
        sb3.append(" = ");
        sb3.append(7);
        sb3.append(" AND ");
        sb3.append("media_size");
        sb3.append(" = ");
        sb3.append(6);
        sb3.append(" ORDER BY ");
        sb3.append("sort_id");
        sb3.append(" DESC LIMIT 1");
        A01 = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append("SELECT ");
        sb4.append(str);
        sb4.append(" FROM ");
        sb4.append("message_system AS message_system");
        sb4.append(" JOIN ");
        sb4.append("available_message_view AS message");
        sb4.append(" ON message_system.message_row_id = message._id");
        sb4.append(" WHERE ");
        sb4.append("chat_row_id = ?");
        sb4.append(" AND ");
        sb4.append("from_me = 1");
        sb4.append(" AND ");
        sb4.append("message_type = 7");
        sb4.append(" AND ");
        sb4.append("message_system.action_type = 6");
        sb4.append(" ORDER BY sort_id DESC");
        sb4.append(" LIMIT 1");
        A02 = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append("SELECT ");
        sb5.append(str);
        sb5.append(" FROM ");
        sb5.append("available_message_view");
        sb5.append(" WHERE ");
        sb5.append("chat_row_id");
        sb5.append(" = ?  AND ");
        sb5.append("message_type");
        sb5.append(" NOT IN ('");
        sb5.append(8);
        sb5.append("' , '");
        sb5.append(10);
        sb5.append("' , '");
        sb5.append(12);
        sb5.append("') AND (");
        sb5.append("from_me");
        sb5.append(" = 0 OR (");
        sb5.append("message_type");
        sb5.append(" = '");
        sb5.append(7);
        sb5.append("' AND ");
        sb5.append("media_size");
        sb5.append(" = ");
        sb5.append(4);
        sb5.append(" AND ");
        sb5.append("media_duration");
        sb5.append(" = 1) OR (");
        sb5.append("message_type");
        sb5.append("=");
        sb5.append(7);
        sb5.append(" AND ");
        sb5.append("media_size");
        sb5.append(" = ");
        sb5.append(12);
        sb5.append(" AND ");
        sb5.append("media_duration");
        sb5.append(" = 1)) ORDER BY ");
        sb5.append("sort_id");
        sb5.append(" DESC LIMIT ?");
        A06 = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append("SELECT ");
        sb6.append(str);
        sb6.append(" FROM ");
        sb6.append("available_message_view AS message");
        sb6.append(" LEFT JOIN ");
        sb6.append("message_system");
        sb6.append(" AS message_system");
        sb6.append(" ON message_system.message_row_id = message._id");
        sb6.append(" LEFT JOIN ");
        sb6.append("message_system_group");
        sb6.append(" AS system_group");
        sb6.append(" ON message_system.message_row_id = system_group.message_row_id");
        sb6.append(" WHERE ");
        sb6.append("message.chat_row_id = ?");
        sb6.append(" AND ");
        sb6.append("message.message_type NOT IN ('8' , '10' , '12')");
        sb6.append(" AND (");
        sb6.append("message.from_me = 0 OR (message_system.action_type = 4 AND system_group.is_me_joined = 1) OR (message_system.action_type = 12 AND system_group.is_me_joined = 1))");
        sb6.append(" ORDER BY sort_id");
        sb6.append(" DESC LIMIT ?");
        A05 = sb6.toString();
        StringBuilder sb7 = new StringBuilder("SELECT _id FROM message_view WHERE _id > ?  AND chat_row_id = ? AND from_me = 1 AND message_type = 7 AND ");
        sb7.append("media_size IN ");
        AnonymousClass01D r2 = C40171tg.A00;
        sb7.append(C34111ji.A00(((Set) r2.get()).size()));
        A07 = sb7.toString();
        StringBuilder sb8 = new StringBuilder("SELECT _id FROM message_system JOIN message_view ON message_view._id = message_system.message_row_id  WHERE _id > ?  AND chat_row_id = ?  AND action_type IN ");
        sb8.append(C34111ji.A00(((Set) r2.get()).size()));
        A08 = sb8.toString();
        StringBuilder sb9 = new StringBuilder("SELECT key_remote_jid, sum(media_size) as media_sum FROM messages WHERE media_wa_type IN ('0','1','2','3','4','5','9','13','14') AND ");
        sb9.append("key_remote_jid != '");
        sb9.append(C34771kq.A00.getRawString());
        sb9.append("' GROUP BY ");
        sb9.append("key_remote_jid");
        sb9.append(" ORDER BY media_sum DESC");
        A00 = sb9.toString();
    }
}
