package X;

/* renamed from: X.1xm  reason: invalid class name and case insensitive filesystem */
public class C42431xm {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    @Deprecated
    public static final String A0A;
    public static final String A0B;
    @Deprecated
    public static final String A0C;
    @Deprecated
    public static final String A0D;

    static {
        StringBuilder sb = new StringBuilder("SELECT ");
        String str = C16910tr.A00;
        sb.append(str);
        sb.append(" FROM ");
        sb.append("message_view");
        sb.append(" WHERE ");
        sb.append("sort_id");
        sb.append(" IN (SELECT docid FROM ");
        sb.append("message_ftsv2");
        sb.append(" AS ");
        sb.append("message_ftsv2");
        sb.append(", ");
        sb.append("available_message_view");
        sb.append(" AS message  WHERE ");
        sb.append("message_ftsv2");
        sb.append(" MATCH ? AND ");
        sb.append("message_ftsv2.docid = message.sort_id) ");
        sb.append(" ORDER BY ");
        sb.append("sort_id");
        sb.append(" DESC");
        A05 = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append("SELECT ");
        sb2.append(str);
        sb2.append(", ");
        sb2.append("docid");
        sb2.append(", ");
        sb2.append("content");
        sb2.append(", ");
        sb2.append("fts_jid");
        sb2.append(" FROM ");
        sb2.append("message_ftsv2 AS fts");
        sb2.append(" JOIN ");
        sb2.append("available_message_view AS message");
        sb2.append(" ON ");
        sb2.append("fts.docid = message.sort_id");
        sb2.append(" WHERE ");
        sb2.append("message_ftsv2");
        sb2.append(" MATCH ? ");
        A08 = sb2.toString();
        StringBuilder sb3 = new StringBuilder();
        sb3.append("SELECT ");
        sb3.append(C34111ji.A01("message", str));
        sb3.append(", links.link_index AS link_index FROM ");
        sb3.append("available_message_view AS message");
        sb3.append(" INNER JOIN ");
        sb3.append("message_link AS links");
        sb3.append(" ON message.");
        sb3.append("_id");
        sb3.append(" = links.");
        sb3.append("message_row_id");
        sb3.append(" WHERE message.");
        sb3.append("sort_id");
        sb3.append(" IN ");
        sb3.append("(SELECT docid FROM message_ftsv2 WHERE content MATCH ? )");
        sb3.append(" ORDER BY sort_id DESC");
        A04 = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append("SELECT ");
        sb4.append(str);
        sb4.append(" FROM ");
        sb4.append("available_message_view");
        sb4.append(" WHERE ");
        sb4.append("sort_id");
        sb4.append(" IN ");
        sb4.append("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id AND message.starred = 1 AND (message_type != '7'))");
        sb4.append(" ORDER BY sort_id DESC");
        A0B = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append("SELECT ");
        sb5.append(str);
        sb5.append(" FROM ");
        sb5.append("message_view");
        sb5.append(" WHERE ");
        sb5.append("_id");
        sb5.append(" IN (SELECT docid FROM ");
        sb5.append("messages_fts");
        sb5.append(" AS messages_fts, ");
        sb5.append("available_message_view");
        sb5.append(" AS message  WHERE content MATCH ? AND messages_fts.docid = message.");
        sb5.append("_id");
        sb5.append(" AND message.");
        sb5.append("message_type");
        sb5.append(" IN ('");
        sb5.append(9);
        sb5.append("' , '");
        sb5.append(26);
        sb5.append("' ) AND ");
        sb5.append("message.chat_row_id = ?) ");
        sb5.append(" ORDER BY ");
        sb5.append("sort_id");
        sb5.append(" DESC");
        A00 = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append("SELECT ");
        sb6.append(str);
        sb6.append(", links.link_index AS link_index FROM ");
        sb6.append("available_message_view AS message");
        sb6.append(", (SELECT message_row_id, link_index FROM ");
        sb6.append("messages_links AS links");
        sb6.append(" WHERE links.key_remote_jid=? AND message_row_id IN ( SELECT docid FROM ");
        sb6.append("messages_fts");
        sb6.append(", ");
        sb6.append("message_view");
        sb6.append(" AS message WHERE content MATCH ? AND ");
        sb6.append("messages_fts");
        sb6.append(".docid = message.");
        sb6.append("_id");
        sb6.append(")) links WHERE ");
        sb6.append("message._id = links.message_row_id");
        sb6.append(" ORDER BY ");
        sb6.append("_id");
        sb6.append(" DESC");
        A01 = sb6.toString();
        StringBuilder sb7 = new StringBuilder();
        sb7.append("SELECT ");
        sb7.append(str);
        sb7.append(", links.link_index AS link_index FROM ");
        sb7.append("available_message_view");
        sb7.append(" AS message, (SELECT message_row_id, link_index FROM ");
        sb7.append("messages_links");
        sb7.append(" WHERE message_row_id IN ( SELECT docid FROM ");
        sb7.append("message_ftsv2");
        sb7.append(", ");
        sb7.append("message_view");
        sb7.append(" AS message WHERE ");
        sb7.append("message_ftsv2");
        sb7.append(" MATCH ? AND ");
        sb7.append("message_ftsv2");
        sb7.append(".docid = message.");
        sb7.append("_id");
        sb7.append(")) links WHERE message.");
        sb7.append("_id");
        sb7.append(" = links.message_row_id ORDER BY ");
        sb7.append("_id");
        sb7.append(" DESC");
        A02 = sb7.toString();
        StringBuilder sb8 = new StringBuilder();
        sb8.append("SELECT ");
        sb8.append(str);
        sb8.append(", links.link_index AS link_index FROM ");
        sb8.append("message_view AS message");
        sb8.append(", ");
        sb8.append("(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, available_message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links");
        sb8.append(" WHERE ");
        sb8.append("message._id = links.message_row_id ");
        sb8.append(" ORDER BY _id DESC");
        A03 = sb8.toString();
        StringBuilder sb9 = new StringBuilder();
        sb9.append(str);
        sb9.append(", ");
        sb9.append("messages_fts.docid AS docid");
        sb9.append(", ");
        sb9.append("messages_fts.content AS content");
        String obj = sb9.toString();
        StringBuilder sb10 = new StringBuilder();
        sb10.append("SELECT ");
        sb10.append(obj);
        sb10.append(" FROM ");
        sb10.append("message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        sb10.append(" WHERE content MATCH ?");
        A07 = sb10.toString();
        StringBuilder sb11 = new StringBuilder();
        sb11.append("SELECT ");
        sb11.append(obj);
        sb11.append(" FROM ");
        sb11.append("available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        sb11.append(" WHERE content MATCH ? AND ");
        sb11.append("chat_row_id = ?");
        A06 = sb11.toString();
        StringBuilder sb12 = new StringBuilder();
        sb12.append("SELECT ");
        sb12.append(str);
        sb12.append(" FROM ");
        sb12.append("message_view");
        sb12.append(" WHERE ");
        sb12.append("_id");
        sb12.append(" IN ");
        sb12.append("( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n");
        sb12.append(" ORDER BY _id DESC");
        A0C = sb12.toString();
        StringBuilder sb13 = new StringBuilder();
        sb13.append("SELECT ");
        sb13.append(str);
        sb13.append(" FROM ");
        sb13.append("message_view");
        sb13.append(" WHERE ");
        sb13.append("sort_id");
        sb13.append(" IN ");
        sb13.append("( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id\n   AND message.starred = 1   AND (message_type != '7'))\n");
        sb13.append(" ORDER BY ");
        sb13.append("sort_id");
        sb13.append(" DESC");
        A0D = sb13.toString();
        StringBuilder sb14 = new StringBuilder();
        sb14.append("SELECT ");
        sb14.append(str);
        sb14.append(" FROM ");
        sb14.append("available_message_view");
        sb14.append(" WHERE ");
        sb14.append("_id");
        sb14.append(" IN ");
        sb14.append("(SELECT docid FROM messages_fts AS messages_fts, message_view AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))");
        sb14.append(" ORDER BY _id DESC");
        A0A = sb14.toString();
        StringBuilder sb15 = new StringBuilder();
        sb15.append("SELECT ");
        sb15.append(str);
        sb15.append(" FROM ");
        sb15.append("available_message_view AS message");
        sb15.append(" WHERE ");
        sb15.append("sort_id");
        sb15.append(" IN ");
        sb15.append("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id)");
        sb15.append(" AND ");
        sb15.append("message.keep_in_chat = 1");
        sb15.append(" AND ");
        sb15.append("(message_type != '7')");
        sb15.append(" ORDER BY sort_id DESC");
        A09 = sb15.toString();
    }
}
