package X;

/* renamed from: X.2Tn  reason: invalid class name and case insensitive filesystem */
public abstract class C49532Tn {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;

    static {
        StringBuilder sb = new StringBuilder("   SELECT ");
        String str = C16910tr.A00;
        sb.append(str);
        sb.append(" FROM ");
        sb.append("available_message_view");
        sb.append(" WHERE ");
        sb.append("_id > ? ");
        sb.append(" ORDER BY ");
        sb.append("_id ASC");
        sb.append(" LIMIT ?");
        A00 = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append("   SELECT ");
        sb2.append(str);
        sb2.append(" FROM ");
        sb2.append("message_view");
        sb2.append(" WHERE ");
        sb2.append("_id > ? ");
        sb2.append(" ORDER BY ");
        sb2.append("_id ASC");
        sb2.append(" LIMIT ?");
        A01 = sb2.toString();
        StringBuilder sb3 = new StringBuilder("SELECT ");
        sb3.append(C40551uJ.A01);
        sb3.append(", ");
        sb3.append("messages.key_remote_jid AS parent_key_remote_jid, ");
        sb3.append("messages._id AS parent_row_id");
        sb3.append(" FROM ");
        sb3.append("messages AS messages");
        sb3.append(" LEFT JOIN ");
        sb3.append("messages_quotes");
        sb3.append(" ON ");
        sb3.append("messages.quoted_row_id = messages_quotes._id");
        sb3.append(" LEFT JOIN ");
        sb3.append("jid AS chat_jid ON messages_quotes.key_remote_jid = chat_jid.raw_string");
        sb3.append(" LEFT JOIN ");
        sb3.append("chat AS chat ON chat.jid_row_id = chat_jid._id");
        sb3.append(" WHERE ");
        sb3.append("messages._id > ?");
        sb3.append(" ORDER BY ");
        sb3.append("messages._id ASC");
        sb3.append(" LIMIT ?");
        A03 = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append("SELECT ");
        String str2 = AnonymousClass1WW.A00;
        sb4.append(C34111ji.A01("messages", str2));
        sb4.append(", messages.");
        sb4.append("key_remote_jid");
        sb4.append(" FROM ");
        sb4.append("messages");
        sb4.append(" AS messages LEFT JOIN ");
        sb4.append("missed_call_logs AS missed_call_logs");
        sb4.append(" ON messages.");
        sb4.append("_id");
        sb4.append(" = missed_call_logs.message_row_id WHERE ");
        sb4.append("messages._id > ? ");
        sb4.append(" AND ");
        sb4.append("media_wa_type = 10");
        sb4.append(" AND missed_call_logs._id IS NULL");
        sb4.append(" ORDER BY _id ASC");
        sb4.append(" LIMIT ?");
        A02 = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append("SELECT ");
        sb5.append(str2);
        sb5.append(", ");
        sb5.append("key_remote_jid");
        sb5.append(" FROM ");
        sb5.append("messages");
        sb5.append(" WHERE ");
        sb5.append("_id > ?");
        sb5.append(" AND ");
        sb5.append("media_wa_type IN (0,7)");
        sb5.append(" ORDER BY ");
        sb5.append("_id");
        sb5.append(" ASC LIMIT ?");
        A04 = sb5.toString();
    }
}
