package com.mod.bomfab;

import com.obwhatsapp.R;

public final class R$styleable {
    public static final int[] FloatingActionButton = {R.anim.abc_grow_fade_in_from_bottom, R.anim.alpha, R.anim.keylines, R.anim.statusBarBackground, R.anim.layout_behavior, R.anim.layout_anchor, R.anim.layout_keyline, R.anim.abc_popup_enter, R.anim.abc_popup_exit, R.anim.abc_shrink_fade_out_from_bottom, R.anim.fontProviderAuthority, R.anim.fontProviderPackage, R.attr.attr0345, R.anim.fontProviderCerts, R.anim.fontProviderFetchStrategy, R.anim.fontProviderFetchTimeout, R.anim.fontStyle, R.anim.font, R.anim.fontWeight, R.anim.fontVariationSettings};
    public static final int FloatingActionButton_fab_colorDisabled = 2;
    public static final int FloatingActionButton_fab_colorNormal = 0;
    public static final int FloatingActionButton_fab_colorPressed = 1;
    public static final int FloatingActionButton_fab_colorRipple = 3;
    public static final int FloatingActionButton_fab_elevationCompat = 13;
    public static final int FloatingActionButton_fab_hideAnimation = 11;
    public static final int FloatingActionButton_fab_label = 12;
    public static final int FloatingActionButton_fab_progress = 18;
    public static final int FloatingActionButton_fab_progress_backgroundColor = 15;
    public static final int FloatingActionButton_fab_progress_color = 14;
    public static final int FloatingActionButton_fab_progress_indeterminate = 16;
    public static final int FloatingActionButton_fab_progress_max = 17;
    public static final int FloatingActionButton_fab_progress_showBackground = 19;
    public static final int FloatingActionButton_fab_shadowColor = 5;
    public static final int FloatingActionButton_fab_shadowRadius = 6;
    public static final int FloatingActionButton_fab_shadowXOffset = 7;
    public static final int FloatingActionButton_fab_shadowYOffset = 8;
    public static final int FloatingActionButton_fab_showAnimation = 10;
    public static final int FloatingActionButton_fab_showShadow = 4;
    public static final int FloatingActionButton_fab_size = 9;
    public static final int[] FloatingActionMenu = {R.anim.ttcIndex, R.anim.anim0015, R.anim.anim0016, R.anim.anim0017, R.anim.anim0018, R.anim.anim0019, R.anim.anim001a, R.anim.anim001b, R.anim.anim001c, R.anim.anim001d, R.anim.anim001e, R.anim.anim001f, R.anim.anim0020, R.anim.anim0021, R.anim.anim0022, R.anim.abc_tooltip_enter, R.anim.abc_tooltip_exit, R.anim.anim0025, R.anim.anim0026, R.anim.anim0027, R.anim.anim0028, R.anim.anim0029, R.anim.anim002a, R.anim.anim002b, R.anim.anim002c, R.anim.anim002d, R.anim.anim002e, R.anim.anim002f, R.anim.anim0030, R.anim.anim0031, R.anim.anim0032, R.anim.anim0033, R.anim.anim0034, R.anim.anim0035, R.anim.anim0036, R.anim.anim0037, R.anim.anim0038, R.anim.anim0039, R.anim.bottom_down};
    public static final int FloatingActionMenu_menu_animationDelayPerItem = 19;
    public static final int FloatingActionMenu_menu_backgroundColor = 35;
    public static final int FloatingActionMenu_menu_buttonSpacing = 1;
    public static final int FloatingActionMenu_menu_buttonToggleAnimation = 20;
    public static final int FloatingActionMenu_menu_colorNormal = 31;
    public static final int FloatingActionMenu_menu_colorPressed = 32;
    public static final int FloatingActionMenu_menu_colorRipple = 33;
    public static final int FloatingActionMenu_menu_fab_hide_animation = 38;
    public static final int FloatingActionMenu_menu_fab_label = 36;
    public static final int FloatingActionMenu_menu_fab_show_animation = 37;
    public static final int FloatingActionMenu_menu_fab_size = 24;
    public static final int FloatingActionMenu_menu_icon = 18;
    public static final int FloatingActionMenu_menu_labels_colorNormal = 14;
    public static final int FloatingActionMenu_menu_labels_colorPressed = 15;
    public static final int FloatingActionMenu_menu_labels_colorRipple = 16;
    public static final int FloatingActionMenu_menu_labels_cornerRadius = 12;
    public static final int FloatingActionMenu_menu_labels_customFont = 26;
    public static final int FloatingActionMenu_menu_labels_ellipsize = 22;
    public static final int FloatingActionMenu_menu_labels_hideAnimation = 4;
    public static final int FloatingActionMenu_menu_labels_margin = 2;
    public static final int FloatingActionMenu_menu_labels_maxLines = 23;
    public static final int FloatingActionMenu_menu_labels_padding = 9;
    public static final int FloatingActionMenu_menu_labels_paddingBottom = 8;
    public static final int FloatingActionMenu_menu_labels_paddingLeft = 6;
    public static final int FloatingActionMenu_menu_labels_paddingRight = 7;
    public static final int FloatingActionMenu_menu_labels_paddingTop = 5;
    public static final int FloatingActionMenu_menu_labels_position = 17;
    public static final int FloatingActionMenu_menu_labels_showAnimation = 3;
    public static final int FloatingActionMenu_menu_labels_showShadow = 13;
    public static final int FloatingActionMenu_menu_labels_singleLine = 21;
    public static final int FloatingActionMenu_menu_labels_style = 25;
    public static final int FloatingActionMenu_menu_labels_textColor = 10;
    public static final int FloatingActionMenu_menu_labels_textSize = 11;
    public static final int FloatingActionMenu_menu_openDirection = 34;
    public static final int FloatingActionMenu_menu_shadowColor = 27;
    public static final int FloatingActionMenu_menu_shadowRadius = 28;
    public static final int FloatingActionMenu_menu_shadowXOffset = 29;
    public static final int FloatingActionMenu_menu_shadowYOffset = 30;
    public static final int FloatingActionMenu_menu_showShadow = 0;
}
